"""empty message

Revision ID: 0e3a7e3d691d
Revises: a0a902e9fba9
Create Date: 2018-10-15 01:48:42.593049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e3a7e3d691d'
down_revision = 'a0a902e9fba9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_client', sa.Column('client_name', sa.String(length=100), nullable=True))
    op.add_column('oauth2_client', sa.Column('client_uri', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('contact', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('expires_at', sa.Integer(), nullable=False))
    op.add_column('oauth2_client', sa.Column('grant_type', sa.Text(), nullable=False))
    op.add_column('oauth2_client', sa.Column('i18n_metadata', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('issued_at', sa.Integer(), nullable=False))
    op.add_column('oauth2_client', sa.Column('jwks_text', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('jwks_uri', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('logo_uri', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('policy_uri', sa.Text(), nullable=True))
    op.add_column('oauth2_client', sa.Column('redirect_uri', sa.Text(), nullable=False))
    op.add_column('oauth2_client', sa.Column('response_type', sa.Text(), nullable=False))
    op.add_column('oauth2_client', sa.Column('scope', sa.Text(), nullable=False))
    op.add_column('oauth2_client', sa.Column('software_id', sa.String(length=36), nullable=True))
    op.add_column('oauth2_client', sa.Column('software_version', sa.String(length=48), nullable=True))
    op.add_column('oauth2_client', sa.Column('token_endpoint_auth_method', sa.String(length=48), nullable=True))
    op.add_column('oauth2_client', sa.Column('tos_uri', sa.Text(), nullable=True))
    op.alter_column('oauth2_client', 'client_secret',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.add_column('oauth2_code', sa.Column('auth_time', sa.Integer(), nullable=False))
    op.add_column('oauth2_code', sa.Column('response_type', sa.Text(), nullable=True))
    op.add_column('oauth2_token', sa.Column('issued_at', sa.Integer(), nullable=False))
    op.add_column('oauth2_token', sa.Column('revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth2_token', 'revoked')
    op.drop_column('oauth2_token', 'issued_at')
    op.drop_column('oauth2_code', 'response_type')
    op.drop_column('oauth2_code', 'auth_time')
    op.alter_column('oauth2_client', 'client_secret',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('oauth2_client', 'tos_uri')
    op.drop_column('oauth2_client', 'token_endpoint_auth_method')
    op.drop_column('oauth2_client', 'software_version')
    op.drop_column('oauth2_client', 'software_id')
    op.drop_column('oauth2_client', 'scope')
    op.drop_column('oauth2_client', 'response_type')
    op.drop_column('oauth2_client', 'redirect_uri')
    op.drop_column('oauth2_client', 'policy_uri')
    op.drop_column('oauth2_client', 'logo_uri')
    op.drop_column('oauth2_client', 'jwks_uri')
    op.drop_column('oauth2_client', 'jwks_text')
    op.drop_column('oauth2_client', 'issued_at')
    op.drop_column('oauth2_client', 'i18n_metadata')
    op.drop_column('oauth2_client', 'grant_type')
    op.drop_column('oauth2_client', 'expires_at')
    op.drop_column('oauth2_client', 'contact')
    op.drop_column('oauth2_client', 'client_uri')
    op.drop_column('oauth2_client', 'client_name')
    # ### end Alembic commands ###

