version: '3.3'
services:

  client: 
    restart: always
    ports:
      - ${TB_MOBILE_EXTERNAL_PORT:-3060}:3000
    build:
      context: ${TB_MOBILE_CONTEXT:-https://github.com/uwcirg/tb-mobile-app.git}
    stdin_open: true
    tty: true
    command: yarn start
    environment:
      NODE_ENV: development
      REACT_APP_API_PATH:
      REACT_APP_REDIRECT_PATH:
      REACT_APP_CPRO_PATH:
      REACT_APP_CLIENT_ID:

  web:
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - ${WEB_EXTERNAL_PORT:-5061}:${TB_API_INTERNAL_PORT:-5000}
    volumes:
      - "web:/usr/src/app"
    links:
      - mpower-db
      - tbapp-db
    stdin_open: true
    command: /usr/local/bin/gunicorn -w 2 -b :5000 tbapi_app:app
    
    tty: true
    depends_on:
      - mpower-db
      - tbapp-db
    environment:
      CPRO_DATABASE_USER: mpower
      CPRO_DATABASE_PASSWORD: mpower
      CPRO_DATABASE_NAME: mpower_demo
      TB_DATABASE_USER: tbapi
      TB_DATABASE_PASSWORD: tbapi
      TB_DATABASE_NAME: tbapi

      GUNICORN_ACCESSLOG: '-'
      GUNICORN_LOG_FILE: '-'
      GUNICORN_LOG_LEVEL: debug

      WAIT_HOSTS: mpower-db:3306, tbapp-db:3306
      WAIT_BEFORE_HOSTS: 2
      FLASK_APP: "tbapi_app.py"
      FLASK_DEBUG: 1
      AUTHLIB_INSECURE_TRANSPORT: 'true'
      MODE: 'dev'
      REACT_APP_CLIENT_PATH:
    networks:
      - tbapi

  nginx:
    restart: always
    build: ./nginx
    ports:
      - ${TB_API_EXTERNAL_PORT:-5060}:80
    volumes:
      - web:/www/static
    depends_on:
      - web
    networks:
      - tbapi
    environment:
      TB_API_INTERNAL_PORT: ${TB_API_INTERNAL_PORT:-5000}

  cpro:
    restart: always
    build:
      context: ${CPRO_CONTEXT:-https://fake-username:REPO_ACCESS_TOKEN@gitlab.cirg.washington.edu/svn/dhair2.git#feature/tb_mpower-styling}
      dockerfile: docker/Dockerfile
    ports:
      - ${CPRO_EXTERNAL_PORT:-8080}:80
    environment:
      HTTPS: 'true'
      INSTANCE_ID: mpower_tb
      CPRO_API_CLIENT_ID:
      REACT_APP_API_PATH:
      REACT_APP_CPRO_PATH:
      REACT_APP_CLIENT_PATH:
      DATABASE_URL: mysql://${CPRO_DATABASE_USER:-mpower}:${CPRO_DATABASE_PASSWORD:-mpower}@mpower-db:3306/${CPRO_DATABASE_NAME:-mpower_demo}
    command: bash -c '
      env &&
      wait-for-it.sh --timeout=30 --host=mpower-db --port=3306 --strict &&
      cake initialize_database &&
      apache2-foreground
      '
    depends_on:
      - mpower-db
    networks:
      - tbapi

  mpower-db:
    restart: always
    image: mysql:5.7
    hostname: mpower-db
    volumes:
      - "./db/sql/mpower-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: mpower-db-volume
        target: /var/lib/mysql
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${CPRO_DATABASE_USER:-mpower}
      MYSQL_PASSWORD: ${CPRO_DATABASE_PASSWORD:-mpower}
      MYSQL_DATABASE: ${CPRO_DATABASE_NAME:-mpower_demo}
    networks:
      - tbapi

  tbapp-db:
    restart: always
    image: mysql:5.7
    hostname: tbapp-db
    volumes:
      - "./db/sql/tbapp-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: tbapp-db-volume
        target: /var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: ${TB_DATABASE_USER:-tbapi}
      MYSQL_PASSWORD: ${TB_DATABASE_PASSWORD:-tbapi}
      MYSQL_DATABASE: ${TB_DATABASE_NAME:-tbapi}
      MYSQL_ROOT_PASSWORD: root
    networks:
      - tbapi

volumes:
  web:
  mpower-db-volume:
  tbapp-db-volume:

networks:
  tbapi:
