version: '3.3'
services:
  web:
    command: bash -c '/wait && flask run --host 0.0.0.0 --port 5000'
    volumes:
      - source: ./webapp
        target: /home/flask/app/web
        type: bind
        read_only: true
    environment:
      FLASK_ENV: development
